import { and, desc, eq, sql } from "drizzle-orm";
import { productCatalog, storeCategories } from "../client/src/data/catalog";
import { adminNotifications, adminSettings, catalogCategories, catalogInventory, catalogMedia, catalogProducts, catalogVariants, couponRedemptions, coupons, customerProfiles, homepageSlots, orderItems, orders, paymentAttempts, users } from "../drizzle/schema";
import { getDb } from "./db";

type Db = NonNullable<Awaited<ReturnType<typeof getDb>>>;
export type ManagedVariantInput = { size: "30ml" | "50ml" | "100ml"; sku: string; price: number; originalPrice?: number | null; stock: number; published?: boolean };
export type ManagedMediaInput = { mediaType: "image" | "video"; url: string; storageKey?: string | null; altText?: string | null; sortOrder?: number; isPrimary?: boolean };
export type ManagedProductInput = { slug: string; name: string; brand: string; categoryName: string; gender: "Men" | "Women" | "Unisex"; fragranceFamilies: string[]; familySummary?: string | null; badge?: string | null; tone?: string; published: boolean; featuredRank?: number; isNew?: boolean; notesTop?: string[]; notesMiddle?: string[]; notesBase?: string[]; longevity?: string | null; sillage?: string | null; concentration?: string | null; ingredients?: string | null; usageInstructions?: string | null; story?: string | null; variants: ManagedVariantInput[]; media: ManagedMediaInput[] };

async function requireDb() { const db = await getDb(); if (!db) throw new Error("Database is not available."); return db; }
const encode = (values?: string[]) => JSON.stringify((values ?? []).map((value) => value.trim()).filter(Boolean));
const dayKey = (value: Date) => value.toISOString().slice(0, 10);
const initialHomepageSlots = [
  { slotKey: "hero", eyebrow: "UKIZ / THE FIRST EDITION", title: "Find a fragrance that keeps its own counsel.", body: "Modern perfume for the moments that do not need to announce themselves.", ctaLabel: "Shop collection", ctaHref: "/shop", imageUrl: "/manus-storage/aurelia-hero_81789348.jpg", enabled: true, sortOrder: 1 },
  { slotKey: "campaign", eyebrow: "THE GIFT EDIT", title: "A small occasion, beautifully held.", body: "A study in quiet generosity.", ctaLabel: "Discover gifts", ctaHref: "/shop?category=Gift%20Sets", imageUrl: "/manus-storage/category-gift_dd0c39e6.jpg", enabled: true, sortOrder: 2 },
  { slotKey: "story", eyebrow: "THE HOUSE", title: "Made slowly enough to mean something.", body: "A considered approach to contemporary fragrance.", ctaLabel: "Read our story", ctaHref: "/", imageUrl: "/manus-storage/aurelia-ingredient-study_98925c67.jpg", enabled: true, sortOrder: 3 },
  { slotKey: "featured-products", eyebrow: "THE FEATURED EDIT", title: "The current house focus", body: "Choose one product to lead the storefront edit.", productSlug: "cypress-veil", enabled: true, sortOrder: 4 },
  { slotKey: "best-sellers", eyebrow: "THE HOUSE EDIT", title: "Bestsellers, chosen often.", body: "Control whether the best-selling product shelf is visible.", enabled: true, sortOrder: 5 },
  { slotKey: "new-arrivals", eyebrow: "JUST ARRIVED", title: "New studies for the season.", body: "Control whether the new-arrivals shelf is visible.", enabled: true, sortOrder: 6 },
];

export async function ensureAdminSeed() {
  const db = await requireDb();
  await db.insert(adminSettings).values({ id: 1, lowStockThreshold: 5 }).onDuplicateKeyUpdate({ set: { id: sql`id` } });
  const existing = (await db.select({ id: catalogProducts.id }).from(catalogProducts).limit(1))[0];
  if (!existing) {
    for (const [index, category] of Array.from(storeCategories.entries())) await db.insert(catalogCategories).values({ slug: category.title.toLowerCase().replace(/\s+/g, "-"), name: category.title, description: category.note, imageUrl: category.image, enabled: true, archived: false, sortOrder: index + 1 });
    const categories = await db.select().from(catalogCategories);
    for (const product of productCatalog) {
    const category = categories.find((entry) => entry.name === product.category);
    const created = await db.insert(catalogProducts).values({ slug: product.slug, name: product.name, brand: product.brand, categoryId: category?.id ?? null, categoryName: product.category, gender: product.gender, fragranceFamilies: encode(product.families), familySummary: product.family, badge: product.badge ?? null, tone: product.tone, published: true, archived: false, featuredRank: product.featuredRank, isNew: product.isNew ?? false, notesTop: encode(product.notes.top), notesMiddle: encode(product.notes.middle), notesBase: encode(product.notes.base), longevity: product.longevity, sillage: product.sillage, concentration: product.concentration, ingredients: product.ingredients, usageInstructions: product.usage, story: product.story });
    const productId = Number((created as unknown as [{ insertId: number }])[0]?.insertId);
    await db.insert(catalogVariants).values(product.variants.map((variant) => ({ productId, size: variant.size, sku: variant.sku, price: String(variant.price), originalPrice: variant.originalPrice ? String(variant.originalPrice) : null, stock: variant.stock, published: true })));
    await db.insert(catalogInventory).values(product.variants.map((variant) => ({ productSlug: product.slug, variantSize: variant.size, stock: variant.stock }))).onDuplicateKeyUpdate({ set: { productSlug: sql`productSlug` } });
    const media = [...product.gallery.map((url, index) => ({ productId, mediaType: "image" as const, url, altText: product.name, sortOrder: index, isPrimary: index === 0 })), ...(product.video ? [{ productId, mediaType: "video" as const, url: product.video, altText: `${product.name} product film`, sortOrder: product.gallery.length, isPrimary: false }] : [])];
      if (media.length) await db.insert(catalogMedia).values(media);
    }
  }
  await db.insert(homepageSlots).values(initialHomepageSlots).onDuplicateKeyUpdate({ set: { slotKey: sql`slotKey` } });
}

async function productBundle(db: Db, productId: number) {
  const product = (await db.select().from(catalogProducts).where(eq(catalogProducts.id, productId)).limit(1))[0];
  if (!product) return undefined;
  const [variants, media] = await Promise.all([db.select().from(catalogVariants).where(eq(catalogVariants.productId, productId)).orderBy(catalogVariants.size), db.select().from(catalogMedia).where(eq(catalogMedia.productId, productId)).orderBy(catalogMedia.sortOrder)]);
  return { product, variants, media };
}

export async function listManagedProducts() { const db = await requireDb(); await ensureAdminSeed(); const products = await db.select().from(catalogProducts).orderBy(desc(catalogProducts.updatedAt)); return Promise.all(products.map((product) => productBundle(db, product.id))); }
export async function listPublishedStorefrontProducts() { const products = await listManagedProducts(); return products.filter((entry) => entry?.product.published && !entry.product.archived); }
export async function getManagedProduct(productId: number) { const db = await requireDb(); await ensureAdminSeed(); return productBundle(db, productId); }

async function writeProduct(db: any, input: ManagedProductInput, productId?: number) {
  const category = (await db.select().from(catalogCategories).where(eq(catalogCategories.name, input.categoryName)).limit(1))[0];
  const base = { slug: input.slug, name: input.name, brand: input.brand, categoryId: category?.id ?? null, categoryName: input.categoryName, gender: input.gender, fragranceFamilies: encode(input.fragranceFamilies), familySummary: input.familySummary?.trim() || null, badge: input.badge?.trim() || null, tone: input.tone?.trim() || "stone", published: input.published, featuredRank: input.featuredRank ?? 999, isNew: input.isNew ?? false, notesTop: encode(input.notesTop), notesMiddle: encode(input.notesMiddle), notesBase: encode(input.notesBase), longevity: input.longevity?.trim() || null, sillage: input.sillage?.trim() || null, concentration: input.concentration?.trim() || null, ingredients: input.ingredients?.trim() || null, usageInstructions: input.usageInstructions?.trim() || null, story: input.story?.trim() || null, updatedAt: new Date() };
  let id = productId;
  if (id) { await db.update(catalogProducts).set(base).where(eq(catalogProducts.id, id)); await db.delete(catalogVariants).where(eq(catalogVariants.productId, id)); await db.delete(catalogMedia).where(eq(catalogMedia.productId, id)); }
  else { const created = await db.insert(catalogProducts).values(base); id = Number((created as unknown as [{ insertId: number }])[0]?.insertId); }
  if (!id) throw new Error("Catalog product could not be saved.");
  await db.insert(catalogVariants).values(input.variants.map((variant) => ({ productId: id!, size: variant.size, sku: variant.sku, price: String(variant.price), originalPrice: variant.originalPrice == null ? null : String(variant.originalPrice), stock: variant.stock, published: variant.published ?? true })));
  if (input.media.length) await db.insert(catalogMedia).values(input.media.map((media, index) => ({ productId: id!, mediaType: media.mediaType, url: media.url, storageKey: media.storageKey ?? null, altText: media.altText ?? null, sortOrder: media.sortOrder ?? index, isPrimary: media.isPrimary ?? index === 0 })));
  await db.insert(catalogInventory).values(input.variants.map((variant) => ({ productSlug: input.slug, variantSize: variant.size, stock: variant.stock }))).onDuplicateKeyUpdate({ set: { stock: sql`values(${catalogInventory.stock})`, updatedAt: new Date() } });
  return productBundle(db, id);
}

export async function createManagedProduct(input: ManagedProductInput) { const db = await requireDb(); await ensureAdminSeed(); return db.transaction((tx) => writeProduct(tx, input)); }
export async function updateManagedProduct(productId: number, input: ManagedProductInput) { const db = await requireDb(); await ensureAdminSeed(); return db.transaction((tx) => writeProduct(tx, input, productId)); }
export async function archiveManagedProduct(productId: number) { const db = await requireDb(); await db.update(catalogProducts).set({ archived: true, published: false, updatedAt: new Date() }).where(eq(catalogProducts.id, productId)); return { success: true }; }

export async function listCategories() { const db = await requireDb(); await ensureAdminSeed(); return db.select().from(catalogCategories).orderBy(catalogCategories.sortOrder); }
export async function listPublishedCategories() { const categories = await listCategories(); return categories.filter((category) => category.enabled && !category.archived); }
export async function saveCategory(input: { id?: number; slug: string; name: string; description?: string | null; imageUrl?: string | null; enabled: boolean; sortOrder: number }) { const db = await requireDb(); if (input.id) await db.update(catalogCategories).set({ slug: input.slug, name: input.name, description: input.description ?? null, imageUrl: input.imageUrl ?? null, enabled: input.enabled, sortOrder: input.sortOrder, updatedAt: new Date() }).where(eq(catalogCategories.id, input.id)); else await db.insert(catalogCategories).values({ slug: input.slug, name: input.name, description: input.description ?? null, imageUrl: input.imageUrl ?? null, enabled: input.enabled, sortOrder: input.sortOrder }); return listCategories(); }
export async function archiveCategory(id: number) { const db = await requireDb(); await db.update(catalogCategories).set({ archived: true, enabled: false, updatedAt: new Date() }).where(eq(catalogCategories.id, id)); return { success: true }; }

export async function listInventory() { const db = await requireDb(); await ensureAdminSeed(); const [variants, products, inventory, settings] = await Promise.all([db.select().from(catalogVariants), db.select().from(catalogProducts), db.select().from(catalogInventory), db.select().from(adminSettings).where(eq(adminSettings.id, 1)).limit(1)]); const threshold = settings[0]?.lowStockThreshold ?? 5; return variants.map((variant) => { const product = products.find((entry) => entry.id === variant.productId); const stock = inventory.find((entry) => entry.productSlug === product?.slug && entry.variantSize === variant.size)?.stock ?? variant.stock; return { ...variant, productName: product?.name ?? "Archived product", productSlug: product?.slug ?? "", stock, lowStock: stock > 0 && stock <= threshold, outOfStock: stock === 0, threshold }; }); }
export async function setInventory(variantId: number, stock: number) { const db = await requireDb(); const variant = (await db.select().from(catalogVariants).where(eq(catalogVariants.id, variantId)).limit(1))[0]; if (!variant) throw new Error("Variant not found."); const product = (await db.select().from(catalogProducts).where(eq(catalogProducts.id, variant.productId)).limit(1))[0]; if (!product) throw new Error("Product not found."); await db.transaction(async (tx) => { await tx.update(catalogVariants).set({ stock, updatedAt: new Date() }).where(eq(catalogVariants.id, variantId)); await tx.insert(catalogInventory).values({ productSlug: product.slug, variantSize: variant.size, stock }).onDuplicateKeyUpdate({ set: { stock, updatedAt: new Date() } }); }); return listInventory(); }
export async function getAdminSettings() { const db = await requireDb(); await ensureAdminSeed(); return (await db.select().from(adminSettings).where(eq(adminSettings.id, 1)).limit(1))[0]; }
export async function saveAdminSettings(lowStockThreshold: number) { const db = await requireDb(); await db.insert(adminSettings).values({ id: 1, lowStockThreshold }).onDuplicateKeyUpdate({ set: { lowStockThreshold, updatedAt: new Date() } }); return getAdminSettings(); }

export async function listCoupons() { const db = await requireDb(); return db.select().from(coupons).orderBy(desc(coupons.updatedAt)); }
export async function saveCoupon(input: { id?: number; code: string; discountType: "percentage" | "flat"; amount: number; minimumOrderAmount: number; expiresAt?: Date | null; usageLimit?: number | null; active: boolean }) { const db = await requireDb(); const base = { code: input.code.toUpperCase(), discountType: input.discountType, amount: String(input.amount), minimumOrderAmount: String(input.minimumOrderAmount), expiresAt: input.expiresAt ?? null, usageLimit: input.usageLimit ?? null, active: input.active, updatedAt: new Date() }; if (input.id) await db.update(coupons).set(base).where(eq(coupons.id, input.id)); else await db.insert(coupons).values({ ...base, usageCount: 0 }); return listCoupons(); }
export async function archiveCoupon(id: number) { const db = await requireDb(); await db.update(coupons).set({ active: false, updatedAt: new Date() }).where(eq(coupons.id, id)); return { success: true }; }

export async function listHomepageSlots() { const db = await requireDb(); await ensureAdminSeed(); return db.select().from(homepageSlots).orderBy(homepageSlots.sortOrder); }
export async function saveHomepageSlot(input: { id?: number; slotKey: string; eyebrow?: string | null; title?: string | null; body?: string | null; ctaLabel?: string | null; ctaHref?: string | null; imageUrl?: string | null; productSlug?: string | null; enabled: boolean; sortOrder: number }) { const db = await requireDb(); const base = { slotKey: input.slotKey, eyebrow: input.eyebrow ?? null, title: input.title ?? null, body: input.body ?? null, ctaLabel: input.ctaLabel ?? null, ctaHref: input.ctaHref ?? null, imageUrl: input.imageUrl ?? null, productSlug: input.productSlug ?? null, enabled: input.enabled, sortOrder: input.sortOrder, updatedAt: new Date() }; if (input.id) await db.update(homepageSlots).set(base).where(eq(homepageSlots.id, input.id)); else await db.insert(homepageSlots).values(base); return listHomepageSlots(); }

export async function listAdminOrders(input?: { query?: string; orderStatus?: string; paymentStatus?: string; from?: Date; to?: Date }) { const db = await requireDb(); const all = await db.select().from(orders).orderBy(desc(orders.createdAt)); return all.filter((order) => { const query = input?.query?.trim().toLowerCase(); return (!query || [order.orderNumber, order.customerName, order.customerEmail, order.customerPhone].some((value) => value?.toLowerCase().includes(query))) && (!input?.orderStatus || order.orderStatus === input.orderStatus) && (!input?.paymentStatus || order.paymentStatus === input.paymentStatus) && (!input?.from || order.createdAt >= input.from) && (!input?.to || order.createdAt <= input.to); }); }
export async function getAdminOrder(orderId: number) { const db = await requireDb(); const order = (await db.select().from(orders).where(eq(orders.id, orderId)).limit(1))[0]; if (!order) return undefined; const [items, attempts] = await Promise.all([db.select().from(orderItems).where(eq(orderItems.orderId, orderId)), db.select().from(paymentAttempts).where(eq(paymentAttempts.orderId, orderId)).orderBy(desc(paymentAttempts.createdAt))]); return { order, items, attempts }; }
export async function updateAdminOrder(input: { orderId: number; orderStatus?: "pending" | "confirmed" | "processing" | "shipped" | "delivered" | "cancelled"; paymentStatus?: "pending" | "failed" | "cancelled" | "refunded" }) { const db = await requireDb(); const order = (await db.select().from(orders).where(eq(orders.id, input.orderId)).limit(1))[0]; if (!order) throw new Error("Order not found."); if (input.orderStatus === "cancelled" && order.paymentStatus === "paid") throw new Error("Paid orders require the refund workflow before cancellation."); if (input.orderStatus === "cancelled" && order.orderStatus !== "cancelled") { const items = await db.select().from(orderItems).where(eq(orderItems.orderId, order.id)); await db.transaction(async (tx) => { for (const item of items) await tx.execute(sql`UPDATE ${catalogInventory} SET ${catalogInventory.stock} = ${catalogInventory.stock} + ${item.quantity} WHERE ${catalogInventory.productSlug} = ${item.productSlug} AND ${catalogInventory.variantSize} = ${item.variantSize}`); await tx.update(orders).set({ orderStatus: "cancelled", paymentStatus: order.paymentStatus === "pending" ? "cancelled" : order.paymentStatus, updatedAt: new Date() }).where(eq(orders.id, order.id)); }); } else await db.update(orders).set({ orderStatus: input.orderStatus ?? order.orderStatus, paymentStatus: input.paymentStatus ?? order.paymentStatus, updatedAt: new Date() }).where(eq(orders.id, order.id)); return getAdminOrder(order.id); }

export async function listCustomers(input?: { query?: string }) { const db = await requireDb(); const [customerRows, profiles, customerOrders] = await Promise.all([db.select().from(users).orderBy(desc(users.createdAt)), db.select().from(customerProfiles), db.select().from(orders)]); const query = input?.query?.trim().toLowerCase(); return customerRows.map((customer) => { const orderHistory = customerOrders.filter((order) => order.userId === customer.id); const profile = profiles.find((entry) => entry.userId === customer.id); return { ...customer, phone: profile?.phone ?? null, orderCount: orderHistory.length, totalSpending: orderHistory.filter((order) => order.paymentStatus === "paid").reduce((sum, order) => sum + Number(order.total), 0) }; }).filter((customer) => !query || [customer.name, customer.email, customer.phone].some((value) => value?.toLowerCase().includes(query))); }
export async function customerOrders(userId: number) { const db = await requireDb(); return db.select().from(orders).where(eq(orders.userId, userId)).orderBy(desc(orders.createdAt)); }

export async function dashboardData() { const db = await requireDb(); await ensureAdminSeed(); const [allOrders, allUsers, allItems, inventory, settings, attempts] = await Promise.all([db.select().from(orders).orderBy(desc(orders.createdAt)), db.select().from(users), db.select().from(orderItems), db.select().from(catalogInventory), getAdminSettings(), db.select().from(paymentAttempts).orderBy(desc(paymentAttempts.createdAt)).limit(12)]); const paid = allOrders.filter((order) => order.paymentStatus === "paid"); const now = new Date(); const today = dayKey(now); const month = today.slice(0, 7); const salesFor = (ordersForPeriod: typeof allOrders) => ordersForPeriod.filter((order) => order.paymentStatus === "paid").reduce((sum, order) => sum + Number(order.total), 0); const salesByDay = new Map<string, number>(); for (const order of paid) { const key = dayKey(order.createdAt); salesByDay.set(key, (salesByDay.get(key) ?? 0) + Number(order.total)); }
  const dailySales = Array.from({ length: 7 }, (_, offset) => { const date = new Date(now); date.setUTCDate(now.getUTCDate() - (6 - offset)); const key = dayKey(date); return { label: key.slice(5), sales: salesByDay.get(key) ?? 0, orders: allOrders.filter((order) => dayKey(order.createdAt) === key).length }; });
  const productSales = new Map<string, { quantity: number; revenue: number }>(); for (const item of allItems) { const entry = productSales.get(item.productName) ?? { quantity: 0, revenue: 0 }; entry.quantity += item.quantity; entry.revenue += item.quantity * Number(item.unitPrice); productSales.set(item.productName, entry); }
  const bestSellers = Array.from(productSales.entries()).map(([name, values]) => ({ name, ...values })).sort((a, b) => b.quantity - a.quantity).slice(0, 5);
  const lowStock = inventory.filter((item) => item.stock <= settings.lowStockThreshold).sort((a, b) => a.stock - b.stock);
  const derivedNotifications = [...allOrders.filter((order) => dayKey(order.createdAt) === today).slice(0, 4).map((order) => ({ id: `order-${order.id}`, notificationType: "new_order" as const, title: `New order ${order.orderNumber}`, body: `৳ ${Number(order.total).toLocaleString("en-BD")} · ${order.customerName ?? "Guest"}`, createdAt: order.createdAt })), ...lowStock.slice(0, 4).map((item) => ({ id: `stock-${item.id}`, notificationType: "low_stock" as const, title: `${item.productSlug} ${item.variantSize} is low`, body: `${item.stock} unit${item.stock === 1 ? "" : "s"} available`, createdAt: item.updatedAt })), ...attempts.filter((attempt) => attempt.status === "failed").slice(0, 3).map((attempt) => ({ id: `payment-${attempt.id}`, notificationType: "payment_issue" as const, title: "Payment needs review", body: attempt.failureReason ?? attempt.providerTransactionId, createdAt: attempt.updatedAt }))].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()).slice(0, 8);
  return { metrics: { totalSales: salesFor(allOrders), todaySales: salesFor(allOrders.filter((order) => dayKey(order.createdAt) === today)), monthlySales: salesFor(allOrders.filter((order) => dayKey(order.createdAt).startsWith(month))), totalOrders: allOrders.length, pendingOrders: allOrders.filter((order) => order.orderStatus === "pending").length, totalCustomers: allUsers.filter((user) => user.role === "user").length, lowStockProducts: lowStock.length }, dailySales, weeklySales: dailySales, monthlySales: Array.from(salesByDay.entries()).slice(-30).map(([label, sales]) => ({ label, sales })), bestSellers, lowStock, notifications: derivedNotifications, orderTrends: dailySales };
}
