import { and, eq, gte, isNull, or, sql } from "drizzle-orm";
import { nanoid } from "nanoid";
import { catalogInventory, cartItems, checkoutSettings, couponRedemptions, coupons, orderItems, orders, addresses, paymentAttempts, catalogProducts, catalogVariants } from "../drizzle/schema";
import { getDb } from "./db";
import { checkoutCatalog, type CheckoutCatalogProduct, type CheckoutSize } from "./checkoutCatalog";
import { ensureAdminSeed } from "./adminDb";
import { CheckoutValidationError, deliveryFor, discountFor, estimatedDeliveryDate, normalizeCheckoutLines, type CheckoutLine, type DeliverySettings, type DeliveryZone } from "./checkoutPolicy";

const defaultSettings: DeliverySettings = { insideDhakaFee: 80, outsideDhakaFee: 150, estimatedInsideDays: 2, estimatedOutsideDays: 4 };
type CustomerInput = { name: string; email: string; phone: string; addressId?: number; address?: { division: string; district: string; thana: string; detailedAddress: string; phone: string }; deliveryInstructions?: string; deliveryZone: DeliveryZone; couponCode?: string; paymentMethod: "cash_on_delivery" | "gateway_pending"; lines?: CheckoutLine[] };
type DbLike = NonNullable<Awaited<ReturnType<typeof getDb>>>;
async function requireDb() { const db = await getDb(); if (!db) throw new Error("Database is not available."); return db; }
async function ensureSeedData(db: DbLike) {
  await db.insert(checkoutSettings).values({ id: 1, insideDhakaFee: String(defaultSettings.insideDhakaFee), outsideDhakaFee: String(defaultSettings.outsideDhakaFee), estimatedInsideDays: defaultSettings.estimatedInsideDays, estimatedOutsideDays: defaultSettings.estimatedOutsideDays }).onDuplicateKeyUpdate({ set: { id: sql`id` } });
  for (const product of checkoutCatalog) for (const variant of product.variants) await db.insert(catalogInventory).values({ productSlug: product.slug, variantSize: variant.size, stock: variant.initialStock }).onDuplicateKeyUpdate({ set: { productSlug: sql`productSlug` } });
}
function asSettings(row: typeof checkoutSettings.$inferSelect): DeliverySettings { return { insideDhakaFee: Number(row.insideDhakaFee), outsideDhakaFee: Number(row.outsideDhakaFee), estimatedInsideDays: row.estimatedInsideDays, estimatedOutsideDays: row.estimatedOutsideDays }; }
function couponRecord(row: typeof coupons.$inferSelect) { return { id: row.id, code: row.code, discountType: row.discountType, amount: Number(row.amount), minimumOrderAmount: Number(row.minimumOrderAmount), expiresAt: row.expiresAt, usageLimit: row.usageLimit, usageCount: row.usageCount, active: row.active }; }
async function getCoupon(db: DbLike, code?: string) { if (!code?.trim()) return undefined; return (await db.select().from(coupons).where(eq(coupons.code, code.trim().toUpperCase())).limit(1))[0]; }
async function readLines(db: DbLike, userId: number | undefined, guestLines?: CheckoutLine[]) { if (userId) return normalizeCheckoutLines((await db.select().from(cartItems).where(eq(cartItems.userId, userId))).map((line) => ({ productSlug: line.productSlug, variantSize: line.variantSize as CheckoutSize, quantity: line.quantity }))); return normalizeCheckoutLines(guestLines ?? []); }
async function readManagedCheckoutCatalog(db: any): Promise<CheckoutCatalogProduct[]> {
  const [products, variants] = await Promise.all([
    db.select().from(catalogProducts).where(and(eq(catalogProducts.published, true), eq(catalogProducts.archived, false))),
    db.select().from(catalogVariants).where(eq(catalogVariants.published, true)),
  ]);
  if (!products.length) return checkoutCatalog;
  return products.map((product: typeof catalogProducts.$inferSelect) => ({
    slug: product.slug,
    name: product.name,
    variants: variants.filter((variant: typeof catalogVariants.$inferSelect) => variant.productId === product.id).map((variant: typeof catalogVariants.$inferSelect) => ({ size: variant.size as CheckoutSize, price: Number(variant.price), sku: variant.sku, initialStock: variant.stock })),
  })).filter((product: CheckoutCatalogProduct) => product.variants.length);
}
export function quoteLines(lines: CheckoutLine[], inventory: Array<typeof catalogInventory.$inferSelect>, catalog: CheckoutCatalogProduct[] = checkoutCatalog) {
  let subtotal = 0; const itemDetails: Array<{ productSlug: string; productName: string; variantSize: CheckoutSize; sku: string; quantity: number; unitPrice: number }> = [];
  for (const line of lines) { const product = catalog.find((entry) => entry.slug === line.productSlug); const variant = product?.variants.find((entry) => entry.size === line.variantSize); if (!product || !variant) throw new CheckoutValidationError("A product in your bag is no longer available."); const inventoryItem = inventory.find((item) => item.productSlug === line.productSlug && item.variantSize === line.variantSize); if (!inventoryItem || inventoryItem.stock < line.quantity) throw new CheckoutValidationError(`${product.name} in ${line.variantSize} no longer has enough stock.`); subtotal += variant.price * line.quantity; itemDetails.push({ productSlug: product.slug, productName: product.name, variantSize: variant.size, sku: variant.sku, quantity: line.quantity, unitPrice: variant.price }); }
  return { subtotal, itemDetails };
}
export async function quoteCheckout(userId: number | undefined, args: { lines?: CheckoutLine[]; deliveryZone: DeliveryZone; couponCode?: string }) {
  const db = await requireDb(); await ensureAdminSeed(); await ensureSeedData(db); const [settingsRow] = await db.select().from(checkoutSettings).where(eq(checkoutSettings.id, 1)); if (!settingsRow) throw new Error("Checkout settings are unavailable."); const lines = await readLines(db, userId, args.lines); const [inventory, catalog] = await Promise.all([db.select().from(catalogInventory), readManagedCheckoutCatalog(db)]); const base = quoteLines(lines, inventory, catalog); const coupon = await getCoupon(db, args.couponCode); if (args.couponCode?.trim() && !coupon) throw new CheckoutValidationError("This coupon could not be found."); const discount = discountFor(base.subtotal, coupon ? couponRecord(coupon) : undefined); const delivery = deliveryFor(args.deliveryZone, asSettings(settingsRow)); return { ...base, deliveryFee: delivery.fee, discount: discount.amount, total: base.subtotal + delivery.fee - discount.amount, couponCode: discount.code, estimatedDeliveryAt: estimatedDeliveryDate(delivery.days), deliveryDays: delivery.days }; }
function formatAddress(input: CustomerInput["address"], instructions?: string) { if (!input) throw new CheckoutValidationError("Choose or enter a delivery address."); return `${input.detailedAddress}\n${input.thana}, ${input.district}, ${input.division}\nPhone: ${input.phone}${instructions ? `\nDelivery note: ${instructions}` : ""}`; }
async function resolveAddress(db: DbLike, userId: number | undefined, input: CustomerInput) { if (input.addressId) { if (!userId) throw new CheckoutValidationError("Please sign in to use a saved address."); const saved = (await db.select().from(addresses).where(and(eq(addresses.id, input.addressId), eq(addresses.userId, userId))).limit(1))[0]; if (!saved) throw new CheckoutValidationError("That saved address is unavailable."); return { division: saved.division, district: saved.district, thana: saved.thana, detailedAddress: saved.detailedAddress, phone: saved.phone }; } return input.address; }
export async function createCheckoutOrder(userId: number | undefined, input: CustomerInput) {
  const db = await requireDb(); await ensureAdminSeed(); await ensureSeedData(db); const lines = await readLines(db, userId, input.lines); const address = await resolveAddress(db, userId, input); if (!input.name.trim() || !input.email.trim() || !input.phone.trim()) throw new CheckoutValidationError("Customer name, email, and phone are required.");
  return db.transaction(async (tx) => { const [settingsRow] = await tx.select().from(checkoutSettings).where(eq(checkoutSettings.id, 1)); if (!settingsRow) throw new Error("Checkout settings are unavailable."); const [inventory, catalog] = await Promise.all([tx.select().from(catalogInventory), readManagedCheckoutCatalog(tx)]); const base = quoteLines(lines, inventory, catalog); const coupon = input.couponCode?.trim() ? (await tx.select().from(coupons).where(eq(coupons.code, input.couponCode.trim().toUpperCase())).limit(1))[0] : undefined; if (input.couponCode?.trim() && !coupon) throw new CheckoutValidationError("This coupon could not be found."); const discount = discountFor(base.subtotal, coupon ? couponRecord(coupon) : undefined); const delivery = deliveryFor(input.deliveryZone, asSettings(settingsRow)); for (const line of lines) { const result = await tx.execute(sql`UPDATE ${catalogInventory} SET ${catalogInventory.stock} = ${catalogInventory.stock} - ${line.quantity} WHERE ${catalogInventory.productSlug} = ${line.productSlug} AND ${catalogInventory.variantSize} = ${line.variantSize} AND ${catalogInventory.stock} >= ${line.quantity}`) as unknown as [{ affectedRows?: number }]; if (!result[0]?.affectedRows) throw new CheckoutValidationError("A selected variant just sold out. Please review your bag."); }
    const estimatedDeliveryAt = estimatedDeliveryDate(delivery.days); const accessToken = nanoid(24); const orderNumber = `AUR-${new Date().getFullYear()}-${nanoid(8).toUpperCase()}`; const created = await tx.insert(orders).values({ userId, orderNumber, orderAccessToken: accessToken, customerName: input.name.trim(), customerEmail: input.email.trim(), customerPhone: input.phone.trim(), subtotal: String(base.subtotal), deliveryFee: String(delivery.fee), discount: String(discount.amount), total: String(base.subtotal + delivery.fee - discount.amount), couponCode: discount.code, deliveryZone: input.deliveryZone, deliveryInstructions: input.deliveryInstructions?.trim() || null, estimatedDeliveryAt, paymentMethod: input.paymentMethod, paymentReference: input.paymentMethod === "gateway_pending" ? `PAY-${nanoid(12).toUpperCase()}` : null, paymentStatus: "pending", orderStatus: "pending", shippingAddress: formatAddress(address, input.deliveryInstructions) }); const orderId = Number((created as unknown as [{ insertId: number }])[0]?.insertId); if (!Number.isFinite(orderId)) throw new Error("Order creation did not return an identifier."); await tx.insert(orderItems).values(base.itemDetails.map((item) => ({ orderId, productSlug: item.productSlug, productName: item.productName, variantSize: item.variantSize, quantity: item.quantity, unitPrice: String(item.unitPrice) }))); if (coupon) { await tx.insert(couponRedemptions).values({ couponId: coupon.id, orderId, userId }); await tx.update(coupons).set({ usageCount: sql`${coupons.usageCount} + 1`, updatedAt: new Date() }).where(and(eq(coupons.id, coupon.id), or(isNull(coupons.usageLimit), gte(coupons.usageLimit, coupon.usageCount)))); }
    if (userId) await tx.delete(cartItems).where(eq(cartItems.userId, userId)); return { orderId, orderNumber, accessToken, total: base.subtotal + delivery.fee - discount.amount, estimatedDeliveryAt };
  });
}
export async function getCheckoutConfirmation(userId: number | undefined, orderNumber: string, accessToken?: string) { const db = await requireDb(); const order = (await db.select().from(orders).where(eq(orders.orderNumber, orderNumber)).limit(1))[0]; if (!order || (order.userId !== userId && order.orderAccessToken !== accessToken)) return undefined; const items = await db.select().from(orderItems).where(eq(orderItems.orderId, order.id)); return { order, items }; }
export async function cancelCheckoutOrder(input: { userId?: number; orderId?: number; orderNumber?: string; accessToken?: string }) { const db = await requireDb(); return db.transaction(async (tx) => { const scope = input.userId && input.orderId ? and(eq(orders.id, input.orderId), eq(orders.userId, input.userId)) : input.orderNumber && input.accessToken ? and(eq(orders.orderNumber, input.orderNumber), eq(orders.orderAccessToken, input.accessToken)) : undefined; if (!scope) throw new CheckoutValidationError("Order cancellation authorization is incomplete."); const order = (await tx.select().from(orders).where(scope).limit(1))[0]; if (!order) throw new CheckoutValidationError("Order not found."); if (order.orderStatus !== "pending" && order.orderStatus !== "confirmed") throw new CheckoutValidationError("This order can no longer be cancelled."); const items = await tx.select().from(orderItems).where(eq(orderItems.orderId, order.id)); for (const item of items) await tx.execute(sql`UPDATE ${catalogInventory} SET ${catalogInventory.stock} = ${catalogInventory.stock} + ${item.quantity} WHERE ${catalogInventory.productSlug} = ${item.productSlug} AND ${catalogInventory.variantSize} = ${item.variantSize}`); const now = new Date(); await tx.update(paymentAttempts).set({ status: "cancelled", failureReason: "Order cancelled before payment completion", processedAt: now, updatedAt: now }).where(and(eq(paymentAttempts.orderId, order.id), or(eq(paymentAttempts.status, "initiated"), eq(paymentAttempts.status, "pending")))); await tx.update(orders).set({ orderStatus: "cancelled", paymentStatus: order.paymentStatus === "pending" ? "cancelled" : order.paymentStatus, updatedAt: now }).where(eq(orders.id, order.id)); return { success: true }; }); }
