import { and, desc, eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { orders, paymentAttempts } from "../drizzle/schema";
import { getDb } from "./db";
import { amountsMatch, callbackFingerprint, isRetryablePayment, outcomeFromSslStatus, PaymentValidationError, type PaymentOutcome } from "./paymentPolicy";

const sslSessionUrl = "https://sandbox.sslcommerz.com/gwprocess/v4/api.php";
const sslValidationUrl = "https://sandbox.sslcommerz.com/validator/api/validationserverAPI.php";
type PaymentAccess = { userId?: number; orderNumber: string; accessToken?: string };
type CallbackKind = "success" | "failed" | "cancelled" | "ipn";
type Db = NonNullable<Awaited<ReturnType<typeof getDb>>>;

async function requireDb() { const db = await getDb(); if (!db) throw new Error("Database is not available."); return db; }
function readCredentials() { const storeId = process.env.SSLCOMMERZ_SANDBOX_STORE_ID; const storePassword = process.env.SSLCOMMERZ_SANDBOX_STORE_PASSWORD; if (!storeId || !storePassword) throw new PaymentValidationError("Sandbox payment credentials are not configured. Use Cash on Delivery or ask the merchant to add SSLCOMMERZ sandbox credentials."); return { storeId, storePassword }; }
export function safeOrigin(origin: string) { try { const url = new URL(origin); const localPreview = url.hostname === "localhost" || url.hostname === "127.0.0.1"; const manusPreview = url.hostname.endsWith(".manus.computer") || url.hostname.endsWith(".manus.space"); if (url.protocol === "https:") return url.origin; if (manusPreview) return `https://${url.host}`; if (localPreview) return url.origin; throw new Error(); } catch { throw new PaymentValidationError("The payment return origin is invalid."); } }
async function ownedOrder(db: Db, access: PaymentAccess) { const order = (await db.select().from(orders).where(eq(orders.orderNumber, access.orderNumber)).limit(1))[0]; if (!order || (order.userId !== access.userId && order.orderAccessToken !== access.accessToken)) throw new PaymentValidationError("This payment request is not available."); return order; }
function paymentReturnUrls(origin: string) { const base = `${safeOrigin(origin)}/api/payments/sslcommerz`; return { success: `${base}/success`, fail: `${base}/failed`, cancel: `${base}/cancel`, ipn: `${base}/ipn` }; }
async function parseGatewaySession(response: Response) { if (!response.ok) throw new PaymentValidationError("The payment gateway could not be reached. Your order has been preserved; please retry payment."); const payload = await response.json() as { status?: string; GatewayPageURL?: string; sessionkey?: string; failedreason?: string }; if (payload.status !== "SUCCESS" || !payload.GatewayPageURL) throw new PaymentValidationError(payload.failedreason || "The payment gateway could not prepare a secure session. Please retry payment."); return payload; }

export async function initiateSslCommerzPayment(access: PaymentAccess & { origin: string }) {
  const db = await requireDb(); const order = await ownedOrder(db, access);
  if (order.paymentMethod === "cash_on_delivery") throw new PaymentValidationError("This order is set for Cash on Delivery and does not require an online payment session.");
  if (!isRetryablePayment(order.paymentStatus, order.orderStatus)) throw new PaymentValidationError("This order is not eligible for another payment attempt.");
  const { storeId, storePassword } = readCredentials(); const transactionId = `AURPAY-${order.id}-${nanoid(10).toUpperCase()}`; const origin = safeOrigin(access.origin); const callbacks = paymentReturnUrls(origin);
  await db.insert(paymentAttempts).values({ orderId: order.id, provider: "sslcommerz_sandbox", providerTransactionId: transactionId, status: "initiated", amount: String(order.total) });
  try {
    const form = new URLSearchParams({ store_id: storeId, store_passwd: storePassword, total_amount: String(order.total), currency: "BDT", tran_id: transactionId, success_url: callbacks.success, fail_url: callbacks.fail, cancel_url: callbacks.cancel, ipn_url: callbacks.ipn, cus_name: order.customerName ?? "Aurelia customer", cus_email: order.customerEmail ?? "customer@example.invalid", cus_add1: (order.shippingAddress ?? "Address unavailable").slice(0, 250), cus_city: "Dhaka", cus_country: "Bangladesh", cus_phone: order.customerPhone ?? "01700000000", shipping_method: "NO", product_name: `Aurelia order ${order.orderNumber}`, product_category: "Fragrance", product_profile: "general" });
    const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 12_000); const response = await fetch(sslSessionUrl, { method: "POST", body: form, signal: controller.signal }).finally(() => clearTimeout(timer)); const session = await parseGatewaySession(response);
    await db.update(paymentAttempts).set({ status: "pending", gatewayUrl: session.GatewayPageURL, sessionKey: session.sessionkey ?? null, gatewayStatus: session.status }).where(eq(paymentAttempts.providerTransactionId, transactionId)); await db.update(orders).set({ paymentReference: transactionId, paymentStatus: "pending", updatedAt: new Date() }).where(eq(orders.id, order.id));
    return { transactionId, gatewayUrl: session.GatewayPageURL, provider: "sslcommerz_sandbox" as const };
  } catch (error) { await db.update(paymentAttempts).set({ status: "failed", failureReason: error instanceof Error ? error.message.slice(0, 1000) : "Unknown gateway session error", processedAt: new Date() }).where(eq(paymentAttempts.providerTransactionId, transactionId)); throw error; }
}

async function validateSslCommerz(validationId: string) { const { storeId, storePassword } = readCredentials(); const url = new URL(sslValidationUrl); url.searchParams.set("val_id", validationId); url.searchParams.set("store_id", storeId); url.searchParams.set("store_passwd", storePassword); url.searchParams.set("format", "json"); const response = await fetch(url, { signal: AbortSignal.timeout(12_000) }); if (!response.ok) throw new PaymentValidationError("We could not verify the provider transaction. Your order remains unpaid until verification succeeds."); return await response.json() as Record<string, string | number | undefined>; }
async function settlePayment(db: Db, attempt: typeof paymentAttempts.$inferSelect, outcome: PaymentOutcome, payload: Record<string, string | undefined>, validationId?: string) {
  const fingerprint = callbackFingerprint(payload); if (attempt.status === "paid" || attempt.callbackFingerprint === fingerprint) return { outcome: attempt.status, idempotent: true };
  const order = (await db.select().from(orders).where(eq(orders.id, attempt.orderId)).limit(1))[0]; if (!order) throw new PaymentValidationError("The associated order is unavailable."); if (order.orderStatus === "cancelled") throw new PaymentValidationError("This order was cancelled before the payment could be confirmed.");
  await db.transaction(async (tx) => { await tx.update(paymentAttempts).set({ status: outcome, validationId: validationId ?? null, callbackFingerprint: fingerprint, gatewayStatus: payload.status ?? null, failureReason: outcome === "paid" ? null : (payload.failedreason ?? payload.error ?? `${outcome} by provider`).slice(0, 1000), processedAt: new Date(), updatedAt: new Date() }).where(eq(paymentAttempts.id, attempt.id)); await tx.update(orders).set({ paymentStatus: outcome, orderStatus: outcome === "paid" ? "confirmed" : order.orderStatus, updatedAt: new Date() }).where(eq(orders.id, order.id)); });
  return { outcome, idempotent: false, orderNumber: order.orderNumber, accessToken: order.orderAccessToken ?? undefined };
}

export async function processSslCommerzCallback(kind: CallbackKind, payload: Record<string, string | undefined>) {
  const db = await requireDb(); const transactionId = payload.tran_id; if (!transactionId) throw new PaymentValidationError("The payment callback is missing its transaction reference."); const attempt = (await db.select().from(paymentAttempts).where(and(eq(paymentAttempts.provider, "sslcommerz_sandbox"), eq(paymentAttempts.providerTransactionId, transactionId))).limit(1))[0]; if (!attempt) throw new PaymentValidationError("The payment callback does not match an active Aurelia transaction.");
  if (kind === "success" || (kind === "ipn" && ["VALID", "VALIDATED"].includes((payload.status ?? "").toUpperCase()))) { const validationId = payload.val_id; if (!validationId) throw new PaymentValidationError("The successful payment callback is missing its validation reference."); const validated = await validateSslCommerz(validationId); if (String(validated.tran_id) !== transactionId || !amountsMatch(Number(attempt.amount), validated.amount) || String(validated.currency ?? "BDT").toUpperCase() !== "BDT") throw new PaymentValidationError("Provider validation did not match this order. Payment has not been marked as paid."); const outcome = outcomeFromSslStatus(String(validated.status)); return settlePayment(db, attempt, outcome, { ...payload, provider_status: String(validated.status), provider_amount: String(validated.amount) }, validationId); }
  const outcome: PaymentOutcome = kind === "cancelled" ? "cancelled" : "failed"; return settlePayment(db, attempt, outcome, payload);
}

export async function paymentStatus(access: PaymentAccess) { const db = await requireDb(); const order = await ownedOrder(db, access); const attempt = (await db.select().from(paymentAttempts).where(eq(paymentAttempts.orderId, order.id)).orderBy(desc(paymentAttempts.createdAt)).limit(1))[0]; return { orderNumber: order.orderNumber, paymentStatus: order.paymentStatus, orderStatus: order.orderStatus, retryable: isRetryablePayment(order.paymentStatus, order.orderStatus), attempt: attempt ? { transactionId: attempt.providerTransactionId, status: attempt.status, gatewayUrl: attempt.gatewayUrl, failureReason: attempt.failureReason } : undefined }; }

export async function simulateSandboxPayment(access: PaymentAccess, outcome: PaymentOutcome | "network_failure") {
  if (process.env.NODE_ENV === "production") throw new PaymentValidationError("The local payment simulator is disabled in production."); const db = await requireDb(); const order = await ownedOrder(db, access); if (!isRetryablePayment(order.paymentStatus, order.orderStatus)) throw new PaymentValidationError("This order is not eligible for a sandbox payment transition."); let attempt = (await db.select().from(paymentAttempts).where(eq(paymentAttempts.orderId, order.id)).orderBy(desc(paymentAttempts.createdAt)).limit(1))[0]; if (!attempt) { const transactionId = `AURSIM-${order.id}-${nanoid(10).toUpperCase()}`; await db.insert(paymentAttempts).values({ orderId: order.id, provider: "sslcommerz_sandbox", providerTransactionId: transactionId, status: "pending", amount: String(order.total) }); attempt = (await db.select().from(paymentAttempts).where(eq(paymentAttempts.providerTransactionId, transactionId)).limit(1))[0]!; }
  if (outcome === "network_failure") { await db.update(paymentAttempts).set({ status: "failed", failureReason: "Simulated provider network failure", processedAt: new Date() }).where(eq(paymentAttempts.id, attempt.id)); return { outcome, retryable: true }; }
  return settlePayment(db, attempt, outcome, { tran_id: attempt.providerTransactionId, status: outcome === "paid" ? "VALID" : outcome.toUpperCase(), source: "local-sandbox" });
}
