/** Product cards surface verified availability, product routing, persistent bag additions, and account-backed wishlist actions. */
import { Heart, ShoppingBag, Star } from "lucide-react";
import { Link } from "wouter";
import type { StoreProduct } from "@/data/catalog";
import { useCart } from "@/contexts/CartContext";
import { useWishlist } from "@/hooks/useWishlist";
const currency = new Intl.NumberFormat("en-BD");
export function ProductCard({ product, compact = false }: { product: StoreProduct; compact?: boolean }) {
  const { add } = useCart(); const { items, toggle } = useWishlist();
  const isOutOfStock = product.stock === 0; const saved = items.some((item) => item.productSlug === product.slug); const preferredSize = product.variants.find((item) => item.size === "50ml" && item.stock > 0)?.size ?? product.variants.find((item) => item.stock > 0)?.size ?? "50ml";
  const handleWishlist = async (event: React.MouseEvent) => { event.preventDefault(); event.stopPropagation(); await toggle(product.slug); };
  const handleCart = async (event: React.MouseEvent) => { event.preventDefault(); event.stopPropagation(); if (isOutOfStock) return; await add(product.slug, preferredSize); };
  return <article className={`commerce-product commerce-product--${product.tone} ${compact ? "commerce-product--compact" : ""}`}><div className="commerce-product__image-wrap"><Link href={`/product/${product.slug}`} className="commerce-product__link" aria-label={`View ${product.name}`}>{product.badge && <span className="commerce-product__badge">{product.badge}</span>}<img className="commerce-product__primary-image" src={product.image} alt={`${product.name} by ${product.brand}`} loading="lazy" /><img className="commerce-product__hover-image" src={product.hoverImage} alt="" loading="lazy" />{isOutOfStock && <span className="commerce-product__stock-overlay">Out of stock</span>}</Link><button className={`wishlist-button ${saved ? "is-saved" : ""}`} onClick={handleWishlist} aria-label={saved ? `Remove ${product.name} from wishlist` : `Save ${product.name} to wishlist`}><Heart size={17} fill={saved ? "currentColor" : "none"} /></button></div><Link href={`/product/${product.slug}`} className="commerce-product__link commerce-product__details"><p className="commerce-product__brand">{product.brand}</p><h3>{product.name}</h3><p className="commerce-product__family">{product.family}</p><div className="commerce-product__rating" aria-label={product.rating ? `${product.rating} stars from ${product.reviewCount ?? 0} verified reviews` : "No verified customer reviews yet"}>{product.rating ? <><Star size={13} fill="currentColor" /><span>{product.rating}</span><small>({product.reviewCount ?? 0})</small></> : <small>Reviews pending</small>}</div></Link><div className="commerce-product__purchase"><div className="commerce-product__price"><strong>৳ {currency.format(product.price)}</strong>{product.originalPrice && <del>৳ {currency.format(product.originalPrice)}</del>}</div><button className="add-to-cart" onClick={handleCart} disabled={isOutOfStock}>{isOutOfStock ? "Unavailable" : "Quick add"}<ShoppingBag size={14} /></button></div><p className={`commerce-product__stock ${isOutOfStock ? "is-out" : ""}`}>{isOutOfStock ? "Currently unavailable" : `${product.stock} available`}</p></article>;
}
